myList=[76,92.3,"hello",True,4,76]
#a
myList.append("apple")
myList.append(76)
print(myList)
#b
myList.insert(3,"cat")
print(myList)
#c
myList.insert(0,99)
print(myList)
#d
print(myList.index("hello"))
#e
print(myList.count(76))
#f
myList.remove(76)
print(myList)
#g
myList.pop(myList.index(True))
print(myList)
